spring:
  application:
    name: serviceConsumer
  main:
    allow-bean-definition-overriding: true
server:
  port: 6545
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:6543/eureka/
feign:
  hystrix:
    enabled: true
management: 
  endpoints:
    web:
      exposure:
        include: "*"
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:6550/users/current
      preferTokenInfo: false
    client:
      clientId: client_1
      clientSecret: 123456
      accessTokenUri: http://localhost:6550/oauth/token
      grantType: client_credentials
      scope: server
      clientAuthenticationScheme: form